---
# tasks file for cluster_control making sure to initialize master servers first
# it installs cronjobs as well for the different kind of servers

- name: Try to start master servers
  block:
    - name: Copy bash script for cronjob
      copy:
        src: "restart.sh"
        dest: "{{ base_install }}/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 775
      
    - name: "Start master servers"
      shell: |
        cd {{ base_install }}; nohup {{ master_dir }}/bin/yb-master --flagfile {{ conf_dir }}/master.conf \
          > {{ base_install }}/master_install.out 2>&1 & sleep 1
      register: master_status
      
    - name: "check if master server started"
      shell: "ps auxww | grep yb-master | egrep -v grep"
      register: pid
      until: "pid.rc == 0"
      retries: 100
      delay: 4
      when: hostvars[inventory_hostname].group_names is search('master')
    - name: Prepare cronjobs and delete previous Yugabyte ones
      cron:
        name: "YugabyteDB Cronjob for {{ item }}"
        state: absent
      with_items:
        - "{{ templates_names }}"
    - name: enable master cronjobs
      include_tasks: crontab_configure.yml
      when: hostvars[inventory_hostname].group_names is search('master')
     
    - name: Check that you can connect (GET) to master db page and it returns a status 200
      uri:
        url: "http://{{ item }}:7000"
      register: master_start_after
      until: "master_start_after.status == 200"
      retries: 30
      delay: 3
      with_items:
        - "{{ master_ips }}"
    - name: "Start tservers servers"
      shell: |
        cd {{ base_install }}; nohup {{ tserver_dir }}/bin/yb-tserver --flagfile {{ conf_dir }}/tserver.conf \
          > {{ base_install }}/tserver_install.out 2>&1 & sleep 1
      register: tserver_status

    - name: "check if master server started"
      shell: "ps auxww | grep yb-tserver | egrep -v grep"
      register: pid
      until: "pid.rc == 0"
      retries: 100
      delay: 4
      when: hostvars[inventory_hostname].group_names is not search('master')
    - name: include cronjobs for tserver
      include_tasks: crontab_configure.yml
      when: hostvars[inventory_hostname].group_names is not search('master')
  rescue:
    - name: Kindly check YugabyteDB logs
      debug: msg="check server {{ public_hostname }} since yugabyte master and/or tservers are noit initializing"
    
